"""create_drone_and_diagnosis_tables

Revision ID: 87660ac77fa1
Revises: 9e3329297947
Create Date: 2026-09-07 21:06:56.555398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87660ac77fa1'
down_revision: Union[str, Sequence[str], None] = '9e3329297947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_flights',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_code', sa.String(length=50), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drone_flights_id'), 'drone_flights', ['id'], unique=False)
    op.create_index(op.f('ix_drone_flights_session_code'), 'drone_flights', ['session_code'], unique=True)
    op.create_index(op.f('ix_drone_flights_user_id'), 'drone_flights', ['user_id'], unique=False)
    op.create_table('drone_scans',
    sa.Column('flight_id', sa.String(length=36), nullable=True),
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['drone_flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drone_scans_crop_id'), 'drone_scans', ['crop_id'], unique=False)
    op.create_index(op.f('ix_drone_scans_flight_id'), 'drone_scans', ['flight_id'], unique=False)
    op.create_index(op.f('ix_drone_scans_id'), 'drone_scans', ['id'], unique=False)
    op.create_table('disease_diagnoses',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('affected_quadrant', sa.String(length=100), nullable=False),
    sa.Column('organic_remedy', sa.Text(), nullable=False),
    sa.Column('chemical_remedy', sa.Text(), nullable=False),
    sa.Column('preventive_plan', sa.Text(), nullable=False),
    sa.Column('raw_inference_metadata', sa.JSON(), nullable=False),
    sa.Column('diagnosed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['drone_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_diagnoses_id'), 'disease_diagnoses', ['id'], unique=False)
    op.create_index(op.f('ix_disease_diagnoses_scan_id'), 'disease_diagnoses', ['scan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disease_diagnoses_scan_id'), table_name='disease_diagnoses')
    op.drop_index(op.f('ix_disease_diagnoses_id'), table_name='disease_diagnoses')
    op.drop_table('disease_diagnoses')
    op.drop_index(op.f('ix_drone_scans_id'), table_name='drone_scans')
    op.drop_index(op.f('ix_drone_scans_flight_id'), table_name='drone_scans')
    op.drop_index(op.f('ix_drone_scans_crop_id'), table_name='drone_scans')
    op.drop_table('drone_scans')
    op.drop_index(op.f('ix_drone_flights_user_id'), table_name='drone_flights')
    op.drop_index(op.f('ix_drone_flights_session_code'), table_name='drone_flights')
    op.drop_index(op.f('ix_drone_flights_id'), table_name='drone_flights')
    op.drop_table('drone_flights')
    # ### end Alembic commands ###
