"""create_khata_and_labor_tables

Revision ID: 9e3329297947
Revises: 5442bd238c96
Create Date: 2026-09-07 21:02:45.358556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3329297947'
down_revision: Union[str, Sequence[str], None] = '5442bd238c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khata_transactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('crop_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khata_transactions_crop_id'), 'khata_transactions', ['crop_id'], unique=False)
    op.create_index(op.f('ix_khata_transactions_id'), 'khata_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_khata_transactions_transaction_date'), 'khata_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_khata_transactions_transaction_type'), 'khata_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_khata_transactions_user_id'), 'khata_transactions', ['user_id'], unique=False)
    op.create_table('labor_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('crop_id', sa.String(length=36), nullable=True),
    sa.Column('laborer_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('daily_wage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_worked', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_records_crop_id'), 'labor_records', ['crop_id'], unique=False)
    op.create_index(op.f('ix_labor_records_id'), 'labor_records', ['id'], unique=False)
    op.create_index(op.f('ix_labor_records_user_id'), 'labor_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labor_records_user_id'), table_name='labor_records')
    op.drop_index(op.f('ix_labor_records_id'), table_name='labor_records')
    op.drop_index(op.f('ix_labor_records_crop_id'), table_name='labor_records')
    op.drop_table('labor_records')
    op.drop_index(op.f('ix_khata_transactions_user_id'), table_name='khata_transactions')
    op.drop_index(op.f('ix_khata_transactions_transaction_type'), table_name='khata_transactions')
    op.drop_index(op.f('ix_khata_transactions_transaction_date'), table_name='khata_transactions')
    op.drop_index(op.f('ix_khata_transactions_id'), table_name='khata_transactions')
    op.drop_index(op.f('ix_khata_transactions_crop_id'), table_name='khata_transactions')
    op.drop_table('khata_transactions')
    # ### end Alembic commands ###
